### ISSUE TITLE
pip install --download has been deprecated

### ISSUE THREAD

**Issue by ki9us** [c9/c9.ide.language.codeintel#3]
Just a heads up... might want to fix the readme.  

```
$ pip install --download /tmp/codeintel codeintel==0.9.3
DEPRECATION: pip install --download has been deprecated and will be removed in the future. Pip now has a download command that should be used instead.
```

**Comment by mouneyrac** [comment]
Hi, just mentioning that the new command line doesn't work and the old one does on my EC2 instances (I just followed the command line of the README without much thinking)

(python2) ubuntu@ip-172-31-25-227:~$ pip download /tmp/codeintel codeintel==0.9.3
Directory '/tmp/codeintel' is not installable. File 'setup.py' not found.

(python2) ubuntu@ip-172-31-25-227:~$ pip install --download /tmp/codeintel codeintel==0.9.3
DEPRECATION: pip install --download has been deprecated and will be removed in the future. Pip now has a download command that should be used instead.
Collecting codeintel==0.9.3
  Downloading CodeIntel-0.9.3.tar.gz (11.9MB)
    100% |████████████████████████████████| 11.9MB 4.9kB/s 
  Saved /tmp/codeintel/CodeIntel-0.9.3.tar.gz
Collecting six (from codeintel==0.9.3)
  Downloading six-1.10.0-py2.py3-none-any.whl
  Saved /tmp/codeintel/six-1.10.0-py2.py3-none-any.whl
Collecting zope.cachedescriptors (from codeintel==0.9.3)
  Downloading zope.cachedescriptors-4.2.0.tar.gz
  Saved /tmp/codeintel/zope.cachedescriptors-4.2.0.tar.gz
Collecting inflector (from codeintel==0.9.3)
  Downloading Inflector-2.0.11.tar.gz
  Saved /tmp/codeintel/Inflector-2.0.11.tar.gz
Collecting subprocess32 (from codeintel==0.9.3)
  Downloading subprocess32-3.2.7.tar.gz (54kB)
    100% |████████████████████████████████| 61kB 623kB/s 
  Saved /tmp/codeintel/subprocess32-3.2.7.tar.gz
Collecting setuptools (from zope.cachedescriptors->codeintel==0.9.3)
  Using cached setuptools-30.2.0-py2.py3-none-any.whl
  Saved /tmp/codeintel/setuptools-30.2.0-py2.py3-none-any.whl
Successfully downloaded codeintel six zope.cachedescriptors inflector subprocess32 setuptools
